app1/urls.py
app_name='app1'

from django.urls import path
from app1.views import *

urlpatterns = [
    path('page1/',page1,name='page1'),
    path('page2/',page2,name='page2'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def page1(request):
    return render (request,'page1.html')

def page2(request):
    return render (request,'page2.html')

templates/page1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UCL</title>
    <link rel="stylesheet" href="{% static 'css/new.css' %}">
</head>
<body>
    <center>
        <h1>UEFA CHAMPIONSHIP LEAGUE NIGHTS R THE BEST</h1>
        <h2>click here to go page2</h2>
        <br>
        <img src="{% static 'images/ucl.jpg' %}" alt="">
    </center>
</body>
</html>

templates/page2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UCL</title>
    <link rel="stylesheet" href="{% static 'css/new.css' %}">
</head>
<body>
    <center>
        <h1>BARCELONA R THE BEST...</h1>
        <a href="{% url 'app1:page1' %}"><h2>click here to go page1</h2></a>
        <br>
        <img src="{% static 'images/msn.jpg' %}" height="800" width="1600" alt="">
    </center>
</body>
</html>